# Configuration file for LepWrap
#=======================================================#
#                       Lep-Map 3                       #
#=======================================================#
# change this to false if you want to skip Lep-Map3
run_lepmap: true

  #----- ParentCall2 ------#
# the filtered VCF file with your genotype likelihoods:
vcf: "mydata.vcf"

# Instructions to create pedigree file: https://sourceforge.net/p/lep-map3/wiki/software/LepMap3 Home/#parentcall2
# the pedigree file associated with your data
pedigree: "pedigree.txt"

# If there are any additional parameters you would like to use for ParentCall2 (e.g. halfSibs=1), add them here
extra_params_ParentCall: "removeNonInformative=1"


  #----- Filtering2 -----#
# data tolerance value-- set this to 0 if you want to skip the Filtering2 module
data_tol: 0

# If there are any additional parameters you would like to use for Filtering2 (e.g. convert2Biallelic=1), add them here
extra_params_Filtering: ""


  #----- SeperateChromosomes2 -----#
# LepWrap will iteratively perform SeperateChromosomes2 for each
# LOD score in the range of lod_min to lod_max

# The minimum LOD for SeperateChromosomes2
lod_min: 10

# The maximum LOD for SeperateChromosomes2
lod_max: 50

# Use only markers with informative father (1), mother(2), both parents(3) or neither parent(0)
informative: "informativeMask=3"

# If there are any additional parameters you would like to use for SeparateChromosomes2 (e.g. distrotionLOD=1), add them here
extra_params_SeparateChromosomes: "sizeLimit=5 distortionLod=1"


  #----- JoinSingles2ALL -----#
# set this to false if you want to skip joining singles (0) to linkage groups
run_joinsingles2all: false

# these are the parameters for JoinSingles2ALL, and are highly data-dependent
# start with lower values for lod_limit and increase as necessary
lod_limit: "lodLimit=2"

# start with lower values for lod_limit and increase as necessary
lod_difference: "lodDifference=2"

# If there are any additional parameters you would like to use for JoinSingles2All (e.g. iterate=1), add them here
extra_params_JoinSingles: "iterate=1 distortionLod=1"
 

  #----- OrderMarkers2 -----#
# LepMak3r will iteratively order markers for each of 1:exp_lg number of chromosomes  
# Set exp_lg to your expected number of chromosomes
exp_lg: 24

# If there are any additional parameters you would like to use for OrderMarkers2 (e.g. hyperPhaser=1), add them here
# I recommend setting numMergeIterations to ~100 (Lep-Map3 default is 6)
extra_params_OrderMarkers: "hyperPhaser=1 useKosambi=1 phasingIterations=2 numMergeIterations=100"


  #----- Edge Trimming -----#
# Edge trimming will examine the first and last X% of markers in a linkage group
# and remove clusters that are N% centimorgans (of the total cM span) away from 
# the next marker. You can "skip" trimming by setting trim_cutoff really high (e.g. 80-100).

# Set edge_length to the percent number of markers you would like to examine from either end of the linkage group
# Value can be an integer or decimal, i.e. 15 is the same as 0.15, which both mean "15%" (10-20 is reasonable)
edge_length: 20

# Set trim_cuttoff to the centiMorgan distance cutoff (5 is reasonable)
trim_cutoff: 100 



  #----- Re-OrderMarkers2 -----#
# The second round of OrderMarkers will use the same basic parameters as the first round (but not the extra params)
# If there are additional parameters you would like to use, add them here:
extra_params_reOrderMarkers: "improveOrder=1 useKosambi=1 numMergeIterations=75"

#----- Calculate Distances -----#
# If you used useKosambi=1 or useMorgan=1 for Ordering/reOrdering, add that same
# parameter to distance_method: 
distance_method: "useKosambi=1"


#=======================================================#
#                       Lep-Anchor                      #
#=======================================================#
# change this to false if you want to skip Lep-Anchor
run_lepanchor: true

# the path to the genome assembly you are trying to anchor
# ideally it is *not* gzipped and ends in .fa, but there are built-in workarounds if it is. 
assembly: "assembly.fasta"

# the number of linkage groups you have
lg_count: 24

# if you have a PAF file of long reads mapped to your genome, add it here, otherwise leave the text as "/dev/null"
PAF_file: "/dev/null"

# if you have a proximity file add it here, otherwise leave the text as "/dev/null".
# This isn't yet implemented in Lep-Anchor, so don't change this.
proximity_file: "/dev/null"


  #----- CleanMap -----#
# If there are any additional parameters you would like to use for CleanMap (e.g. chimericDistance=500), add them here
extra_params_CleanMap: ""


  #----- Map2Bed -----#
# If there are any additional parameters you would like to use for Map2Bed (e.g. markerSupport=4), add them here
extra_params_Map2Bed: ""


  #----- PlaceAndOrientContigs -----#
# choose which of the input types you want to generate by leaving it uncommented
# LepAnchor uses intervals by default, but either works.
#lepanchor_input: "noIntervals=0"  # data is intervals
lepanchor_input: "noIntervals=1"  # data is distances

# The size limit for detecting potential haplotype contigs (default: ~5000)
# Set this value really high (50000+) to ignore haplotype removal in between PlaceOrient iterations
haplotype_limit: 5000

# If there are any additional parameters you would like to use for PlaceAndOrientContigs (e.g. randomOrder=1), add them here
extra_params_PlaceOrient: "keepEmptyIntervals=1 numRuns=10"


  #----- Edge Trimming -----#
# Edge trimming will examine the first and last X% of markers in a linkage group
# and remove clusters that are N% centimorgans (of the total cM span) away from 
# the next marker. You can "skip" trimming by setting  LA_trim_cutoff really high (e.g. 80-100) 

# Set edge_length to the percent number of markers you would like to examine from either end of the linkage group
# Value can be an integer or decimal, i.e. 15 is the same as 0.15, which both mean "15%" (10-15 is reasonable)
LA_edge_length: 20

# Set trim_cuttoff to the centiMorgan distance cutoff (5 is reasonable)
LA_trim_cutoff: 5
