# Configuration file for LepWrap

#### Lep-Map 3 ####
#---------------#
#  ParentCall2  #
#---------------#
# the filtered VCF file with your genotype likelihoods:
vcf: "out.14.missrecode.vcf"

# Instructions to create pedigree file: https://sourceforge.net/p/lep-map3/wiki/LM3 Home/#parentcall2
# the pedigree file associated with your data
pedigree: "pedigree.txt"

#---------------#
#   Filtering2  #
#---------------#
# set this to 0 if you want to skip the Filtering2 module
data_tol: 0.01

#------------------------#
#  SeperateChromosomes2  #
#------------------------#
# LepMak3r will iteratively perform SeperateChromosomes2 for each
# LOD score in the range of lod_min to lod_max

# The minimum LOD for SeperateChromosomes2
lod_min: 1

# The maximum LOD for SeperateChromosomes2
lod_max: 40

# Use only markers with informative father (1), mother(2), both parents(3) or neither parent(0)
informative: "informativeMask=123"

#-------------------#
#  JoinSingles2ALL  #
#-------------------#
# these are the parameters for JoinSingles2ALL, and are highly data-dependent
# start with lower values for lod_limit and increase as necessary
lod_limit: "lodLimit=2"

# start with lower values for lod_limit and increase as necessary
lod_difference: "lodDifference=2"

#-----------------#
#  OrderMarkers2  #
#-----------------#
# LepMak3r will iteratively order markers for each of 1:exp_lg number of chromosomes  

# Set exp_lg to your expected number of chromosomes
exp_lg: 24

# Set iter to the number of iterations you want per chromosome (more is better). Recommend 30 or more
iter: 100

# Set threads_per to the number of threads you would like to use per iteration
threads_per: 2

# Choose your distance method by commenting the line you dont want
dist_method: "useKosambi=1"
#dist_method: "useMorgan=1"

#-----------------#
#  Edge Trimming  #
#-----------------#
# Edge trimming will examine the first and last X% of markers in a linkage group
# and remove clusters that are N centimorgans away from the next marker

# Set edge_length to the percent number of markers you would like to examine from either end of the linkage group
# Value can be an integer or decimal, i.e. 15 is the same as 0.15, which both mean "15%"
edge_length: 15

# Set trim_cuttoff to the centiMorgan distance cutoff (10 is reasonable)
trim_cutoff: 10 


#### Lep-Anchor ####
# change this to true if you also want to run Lep-Anchor
run_anchor: false

# the path to the genome assembly you are trying to anchor
# ideally it *is not* gzipped and ends in .fa, but there are built-in workarounds if it is. 
assembly: "YFT.genome.lastest.fa"

# if you have a PAF file of long reads mapped to your genome, add it here, otherwise leave the text as "none"
PAF_file: "none"

# the number of linkage groups you have
lg_count: 24

# Which system is appropriate for running the HaploMerger2 section? Comment out the one that doesn't apply.
# This is kinda necessary for the correct lastz binaries. If you have a Debian or Arch based system, Ubuntu
# should work (tested for Arch Linux, at least). If using a Fedora/RedHat based system, try the CentOS options.
# If you aren't sure, try "Ubuntu" and see what happens! I'm not actually convinced it matters, but you never know.
OS_info: "Ubuntu"
#OS_info: "CentOS5"
#OS_info: "CentOS6"
